# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-10 00:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anthology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('anthology', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Anthology')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Category')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='birth_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='circa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='author',
            name='death_year',
            field=models.IntegerField(null=True),
        ),
    ]
