# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-10 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20160310_0125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='work',
            new_name='parent',
        ),
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
