# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-30 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20160330_2210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anthology',
            options={'verbose_name_plural': 'anthologies'},
        ),
        migrations.AddField(
            model_name='work',
            name='anthologies',
            field=models.ManyToManyField(to='data.Anthology'),
        ),
    ]
