# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 18:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20160428_1824'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='work',
            unique_together=set([('title', 'parent')]),
        ),
    ]
