# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_auto_20160428_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
