# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 22:08
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_add_title_author_parent_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='birth_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='death_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
