# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 22:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_add_author_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='circa',
            new_name='birth_death_circa',
        ),
    ]
