# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_create_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='genres',
            field=models.ManyToManyField(to='data.Genre'),
        ),
    ]
