# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0018_create_race'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='race',
            options={'verbose_name_plural': 'Racial categories'},
        ),
        migrations.AddField(
            model_name='author',
            name='race',
            field=models.ManyToManyField(to='data.Race'),
        ),
    ]
