# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 23:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0019_add_author_race'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='genres',
            new_name='genre',
        ),
    ]
