# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 23:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0021_create_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Gender'),
        ),
    ]
