# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 00:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0022_add_author_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.Gender'),
        ),
        migrations.AlterField(
            model_name='author',
            name='genre',
            field=models.ManyToManyField(blank=True, to='data.Genre'),
        ),
        migrations.AlterField(
            model_name='author',
            name='race',
            field=models.ManyToManyField(blank=True, to='data.Race'),
        ),
    ]
