# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0023_use_category_base_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
